#' Calculate the voltage for which the current is the maximum value multiplied by r
#'
#'This function calculates the voltage at which the current is "r" (default 0.96
#'as the best fit to the radiation parameter Q) of the maximum value of the
#'characteristic function of the recombination chamber.
#'
#' @param characteristic An object of class "recombination_characteristic"
#' generated by recombination_characteristic().
#' @return An object list U_r_calc representing the calculated voltage and an intermediate parameters.
#' @examples
#' # Generate recombination chamber characteristic
#' characteristic <- recombination_characteristic(seq(1, 1000, by = 1))
#' # Calculate recombination voltage for current = r * max(current)
#' voltage <- calculate_voltage_for_current(characteristic, r = 0.96)
#'
#' @export

calculate_recombination_voltage <- function(characteristic, r=0.96) {
  stopifnot(inherits(characteristic, "recombination_characteristic"), is.numeric(r))

  # Generate a vector needed to determine the saturation current
  U_inv_to_lm <- 1/tail(characteristic$voltage, 10)
  I_inv_to_lm <- 1/tail(characteristic$current, 10)

  # Calculate saturation current (maximum value I.max))
  lm.IU_inv <- lm(I_inv_to_lm ~ U_inv_to_lm)
  I.max <- 1/lm.IU_inv$coefficients[1]

  # Calculate r of the maximum value
  I_r <- closest(characteristic$current, r*I.max)

  # Find corresponding voltage
  voltage_index <- which(characteristic$current == I_r)
  voltage <- characteristic$voltage[voltage_index]

  U_r_calc <- list(U_inv_to_lm = U_inv_to_lm, I_inv_to_lm = I_inv_to_lm)
  U_r_calc$Ur <- voltage

  attr(U_r_calc, 'r') <- r
  attr(U_r_calc, 'Imax') <- I.max

  return(U_r_calc)
}
